### ISSUE TITLE
The find-genes function requires a fix 

### ISSUE THREAD

**Issue by tanksha** [MOZI-AI/annotation-scheme#187]
There is a potential issue with the `find-genes` function. It is supposed to do the following

Before we do the annotation for a given list of genes, we look for the gene:

=> if the genes exist in the atomSpace, proceed to do the annotations

=> If not (i.e one or more genes in the list doesn't exist in the atomspace), then 

a) Check if the gene symbol is outdated and suggest the user to use the current symbol. or/and 
b) Suggest the user for similar gene symbols (matching the name)

But am getting gene doesnt exist message whether the gene has outdated symbol or there are similar named genes. The message is not the same when I try it with list of genes and with just a one gene.
Here are the list of genes I tried with  `SLC35E2, MROH7, MROH7-TTC4, DUSP13, AC078925.1, NDUFA11, TUBGCP6, HDAC6, PSPH, PHF2,DMD`

With the whole bio-atomspace loaded

**Comment by Habush** [comment]
@tanksha please check if this issue still persists

**Comment by tanksha** [comment]
it has been fixed, closing it.
