### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by rekado** [MOZI-AI/annotation-scheme#19]
I would like to contribute to this project, but I cannot seem to find any license.  Could you please clarify under what license (if any) this project is released?

**Comment by Z8lick** [comment]
Hi Rekado,

Thank you for your great interest in contributing to our project. At the
moment we have been deciding on which license works best for us as we are
also a company trying to create a sustainable business around our core
software offering so we may further develop and improve the software and
its overall value to those using the software.

Currently, we are in discussions of having either an Apache 2.0, GPL v2, or
GPL v3 Licenses, we plan to finalize our decision this week.

I'm very interested in how you would like to use and contribute to the
project?

Thank you again and looking forward to building with you!
Best,

Kent Zaitlik

CEO
MOZI.AI

**Comment by rekado** [comment]
>  Currently, we are in discussions of having either an Apache 2.0, GPL v2, or GPL v3 Licenses, we plan to finalize our decision this week.

These are all very good potential licenses.  If you do pick the GPL v2 or v3 (my favourite) please consider including the "or later" upgrade clause to avoid incompatibility with other GPL software in the future: https://www.gnu.org/licenses/license-compatibility.html

This makes sense especially in the Guile world where lots of existing software is licensed under GPL v3 or later.

>  I'm very interested in how you would like to use and contribute to the project? 

I don't have a particular use case (yet), but I'd like to see more Scheme (and especially Guile) in the field of bioinformatics.  I'd like to contribute a number of changes to make the code more idiomatic Scheme: remove the use of `set!`, refactoring to remove duplicated code, using `(ice-9 match)` for pattern matching, arranging code in modules, etc.

**Comment by rekado** [comment]
I'd still like to contribute, so I'm curious whether you've already decided on a license :)

**Comment by Habush** [comment]
@rekado Sorry for the delayed response. I have added a GNU GPL v3 license to the project

**Comment by rekado** [comment]
Thank you!  It may be good to also add license/copyright headers to each of the source files, as this is considered best practise.
