### ISSUE TITLE
Use modules

### ISSUE THREAD

**Issue by rekado** [MOZI-AI/annotation-scheme#21]
Currently, the files in the "fuctions" directory are just a collection of procedure definitions.  Actually using them requires loading them from that file.  The Guile way is to have files define modules, so that they can be used with `(use-modules (my module))` as long as they are on the GUILE_LOAD_PATH.

Using modules would also unlock compilation, which provides a significant performance boost.

**Comment by Habush** [comment]
@rekado You can check whether the PR solves the issue
