### ISSUE TITLE
find-go-term is used inconsistently

### ISSUE THREAD

**Issue by linas** [MOZI-AI/annotation-scheme#83]
Sometimes the first argument to `find-go-term` is passed as a string, and sometimes as an atom. It cannot possibly be both ... well, maybe it can be, but that would be confusing and inefficient..

For example, here it is a string:

https://github.com/MOZI-AI/annotation-scheme/blob/7fc4538ba8fb60fb17fc1a728a078ef4fc3dffc1/annotation/functions.scm#L714-L722

because `(GeneNode a)` can only work if `a` is a string.  Similarly here:

https://github.com/MOZI-AI/annotation-scheme/blob/7fc4538ba8fb60fb17fc1a728a078ef4fc3dffc1/annotation/functions.scm#L337

because `cog-name` returns a string.

However, here:
https://github.com/MOZI-AI/annotation-scheme/blob/7fc4538ba8fb60fb17fc1a728a078ef4fc3dffc1/annotation/gene-go.scm#L39

we can clearly see that the first argument is an atom.

So the code is either buggy, or contains obsolete, non-functional code-blocks ...

**Comment by linas** [comment]
From what I can tell, `find-go-term` is always called with `p` being zero.  Perhaps this is not always the case? 

However, for those cases where it is zero, it would be best to have a function that special-cases this.  The problem is that `find-go-term` has this kind-of complicated recursive structure, which is hard to understand, but disappears if p is zero....

Given how central this function seems to be, providing a description of what it does would be useful.

**Comment by linas** [comment]
Optimizations: in `gene-go.scm`, I see `(string-split namespace #\ )` being done inside a loop, but this is a loop constant, and can be moved outside of the loop.  Now, it might be the case that the guile compiler is smart enough to perform this optimization itself, but I wouldn't count on it.  For readability, just move it out of the loop.

Likewise, the `(if (equal?` should be moved out of the loop, since that is a loop constant as well.  And don't use the string "True", just use #t

**Comment by Habush** [comment]
> Sometimes the first argument to find-go-term is passed as a string, and sometimes as an atom.

Yes this is a bug, I will send a PR.

> From what I can tell, find-go-term is always called with p being zero. Perhaps this is not always the case?

No, it isn't always the case. It is called with the parent option in the gene-go annotation which by default is 0.

>  The problem is that find-go-term has this kind-of complicated recursive structure, which is hard to understand, but disappears if p is zero....

Basically what it is doing is -  if the parent number is specified to be n, then it will find all the 0, 1....n-1, nth parents of a given atom. As there is no "native" way of doing this using the pattern matching functions (or is there?) we have to resort to recursively running the pattern matcher.

**Comment by linas** [comment]
I'm not sure what you are trying to say here. A call to `(cog-incoming-set ATOM)` returns a list of the "parents" (or rather, the containers or "hyperedges") of ATOM (a list of the Links that ATOM appears in).  You don't need the pattern matcher to obtain that. If you want the parents of the parents, etc. then certainly you can call recursively. 

My complaint about complexity is that I tried to rewrite `find-go-term` using srfi-1 `fold` until I realized that I couldn't. It seems that it's doing something complicated, and I can't figure out what that is. I get these run-times:
* parent=0  takes 330 seconds (five and a half minutes)
* parent=1 takes 6023 seconds (hour fourty)
* parent=2 takes 15357 seconds (four hours fifeteen)
so clearly its at the head of an explosive combinatorial search. Making it crystal clear would help performance tuning; right now, its just too complicated a knot for me to untie -- I can't really figure out what its doing. (well, I wasn't able to in the time allotted)

**Comment by mjsduncan** [comment]
we can remove the "parent" option from the GO annotation functionality for the annotation service.  it's utility in connecting features with higher level GO concepts is something that can be done in later inference stages of analysis and isn't necessary for annotation.  is the simplification gained worth spending the time to refactor without it?

**Comment by linas** [comment]
>  is the simplification gained worth spending the time to refactor

There is a factor of 20x slow-down associated with this particular call. (literally: parents=0 takes 300 seconds,  parents=1 take almost 2 hours)  So what is parents=1 actually doing, that it takes 20x longer? There is some complicated knot, tied right here; it needs to be unraveled, flattened out, so that the true source of 20x (and possible ways to fix it) becomes apparent. 

For example: I've already found at least one routine being called hundreds of thousands of times, to recompute the same thing, over and over again. It only needed to be called a handful of times, and the results cached. As it happens, that routine (`find-name`) takes only a tiny fraction of the total elapsed time, so tuning it is not really important.  However, it is not at all obvious that something far more hefty is being called over and over. Keeping code simple, readable makes it much easier to maintain.

The short answer of software-development: it is *always* worth spending the time. Recall why you asked for my help -- you were going bankrupt from https://en.wikipedia.org/wiki/Technical_debt  -- until you pay down your technical debt, you are at risk of destroying the entire project.

**Comment by linas** [comment]
closing, this appears to have been fixed at some point.
