### ISSUE TITLE
is-cellular-component? appears to be buggy?

### ISSUE THREAD

**Issue by linas** [MOZI-AI/annotation-scheme#89]
Reading through the code for `is-cellular-component?` suggests its inefficient and probably buggy.  

Buggy: it performs a loop, and sets a response for every acceptable item in the loop. But only the last response is ever kept! All the other loop iterations are discarded!  Do you really want to discard all answers, keeping only the last one?

Inefficient: the loop could be run in reverse, and terminated upon the first acceptable answer.  This avoids running it for longer than needed.

**Comment by linas** [comment]
similar remarks for `is-compartment`... also things like this: `(if res #t #f)` because `res is already the desired value.  I am guessing that what you really wanted for `is-compartment` is the srfi-1 `any?` function, which returns true if any elements in a list satisfies a predicate, and returns false, if none of them do.

**Comment by linas** [comment]
Pull req #95 is a fix for one of these, I think it does what was intended.

**Comment by linas** [comment]
See pull req #96 for the other fix.

**Comment by Habush** [comment]
@tanksha this looks good to me. But please test it before we merge it.
