### ISSUE TITLE
Performance Status

### ISSUE THREAD

**Issue by linas** [MOZI-AI/annotation-scheme#98]
OK, this is not a bug report, but rather a status update (and a request that someone carry out the work mentioned below)

* I've queued up 9 pull reqs and 11 open issues .. please deal with these. 
* After all of the above, I finally reproduced the `Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS` error when running `gene-pathway-annotation`. I am currently retrying with a version of bdwgc with `./configure --enable-large-config` set to see if that helps.
* I'm fairly certain that the `Too many heap sections` is due to severe memory fragmentation. In particular, the error showed up while guile was using "only" 6GB RAM, of which probably 98% of that is in the atomspace, and not guile itself. ~~(Right now, on a re-run, the process is using 4.1GB RAM, and guile itself has only 26MBytes in the heap, which seems modest enough to me.)~~
* ~~So RAM consumption per-se does not seem to be an issue, neither by the atomspace or guile.~~ Correction: just a few minutes ago, guile went into GC overdrive. Its now trying to GC every10 seconds or so, and it's using almost all CPU cores to do the GC. This happened after about 5 hours runtime, when everything was steady, stable. top/ps aux shows RAM usage suddenly exploded to 10GB RSS and 19GB virt. Currently `(gc-stats)` shows 4GB in the guile heap, and 0.5GB of the guile heap free. ~~No clue what/why/where in the code would cause such a monstrous demand on the heap.~~ Update: this is now fixed in #105. I still don't understand the root-cause of the explosion, but the fix does fix it.
* ~~I'm fairly certain that the excessive usage of deeply nested `GroundedSchemaNodes` is the root cause of the memory fragmentation. (Update: now I'm not so sure)~~ I am now certain that this is not the issue, at all.

~~I'm going to ponder if there is some really clever way to avoid this. However,~~ It might be worthwhile to pre-emptively redesign the code to be flatter, and less recursive.  That means replacing the BindLink/GroundedSchema combination with GetLink and srfi-1 map. Just use GetLink to get lists of things, and use `map` to apply whatever processing is needed to the results.  ~~I'm guessing this will solve this problem, and maybe even improve runtime. Not sure.~~ This is an interesting alternative design to explore, and it might (or might not) make things smaller, faster. I'm not sure. 

Here's one problem with `GroundedSchema`: every time that it is called, the guile subsystem has to be re-entered again, and there is some non-trivial number of microseconds (maybe 50?) needed to do this. It also creates a half-dozen C stack frames, and so you risk over-flowing the C stack, if not careful.  Many years ago, the atomspace code was tuned to minimize both of these effects, and so maybe they are not as severe as I remember them being, but still -- its a potential trouble area. Or not. Maybe all this is OK as is.

See also next comment

**Comment by linas** [comment]
I proposed in #88 that certain simple searches might run faster if done purely in scheme, andor in new custom C++ code.   But the extent of this is completely unknown. I have no idea what the performance difference is.  Also, even if the hit is large, we don't know what fraction of the total performance is affected. So, to that end, we need performance profiles. Here's what I got:

* I tried `linux perf` using recepies from  http://www.brendangregg.com/perf.html but this does not seem to provide any useful info.  It slices and dices the wrong way, for us.
* I tried `(use-modules (statprof))` from https://www.gnu.org/software/guile/manual/html_node/Statprof.html but promptly got a crash from an interrupted system call. Anyway, even avoiding that, it (once again) does not provide the kind of info that is useful for this project.

So the only solution I see right now is to manually instrument the code. This is kind-of tedious and painful, but should be quite revealing.  It should be specific enough to let us know what parts of the system are gobbling up the CPU time (and even memory) and so tuning those can be made a priority. Here's how (see next post)

**Comment by linas** [comment]
So here is a small instrumentation tool I just created:
```
(define (accum-time name)
"
   Maintain performance profile manually.
   Example usage:

      (define actr (accum-time \"foo\"))
      (define bctr (accum-time \"bar\"))
      (actr #:enter? #t) ; start timing foo
      (bctr #:enter? #t) ; start timing bar
      (bctr #:enter? #f) ; stop  timing bar
      (bctr #:enter? #t) ; start timing bar
      (bctr #:enter? #f) ; stop  timing bar
      (bctr #:enter? #t) ; start timing bar
      (bctr #:enter? #f) ; stop  timing bar
      (actr #:enter? #f) ; stop  timing foo
      (actr #:report? #t) ; report foo
      (bctr #:report? #t) ; report bar
"
   (let ((fname name)
         (elapsed 0)
         (calls 0)
         (start 0))
      (lambda* (#:key (enter? #f) (report? #f))
         (if report?
            (format #t "Time: ~9f secs. calls: ~A avg: ~8,1f usec/call for ~A\n"
               (* 1.0e-9 elapsed)
               calls
               (/ (* 1.0e-3 elapsed) calls)
               fname)
            (if enter?
               (set! start (get-internal-real-time))
               (begin
                  (set! elapsed (+ elapsed
                     (- (get-internal-real-time) start)))
                  (set! calls (+ calls 1)))))))
)
```
Here is how I am using it in the code:
```
(define smpdb-ctr (accum-time "smpdb"))
(define reactome-ctr (accum-time "reactome"))
(define find-pathway-genes-ctr (accum-time "find-pathway-genes"))
(define add-pathway-genes-ctr (accum-time "add-pathway-genes"))
(define find-go-term-ctr (accum-time "find-go-term"))
(define find-memberln-ctr (accum-time "find-memberln"))
(define add-go-info-ctr (accum-time "add-go-info"))
(define find-parent-ctr (accum-time "find-parent"))
```
and then, for each of these, I did this:
```
--- a/annotation/functions.scm
+++ b/annotation/functions.scm
@@ -28,7 +28,13 @@
 )
 
 ;;Given an atom and list of namespaces finds the parents of that atom in the specified namespaces
-(define find-parent
+(define-public (find-parent a b)
+       (find-parent-ctr #:enter? #t)
+       (let ((rv (xfind-parent a b)))
+       (find-parent-ctr #:enter? #f)
+       rv))
+       
+(define xfind-parent
 
   (lambda (node namespaces)
         (let (
=
```
It's kind-of tedious to add a bunch of these by hand, so if you have a better idea, do that. Maybe @rekado has some stunt that would be more elegant.  

Then run for a while and then say:
```
(smpdb-ctr #:report? #t)
(reactome-ctr #:report? #t)
(find-pathway-genes-ctr #:report? #t)
(add-pathway-genes-ctr #:report? #t)
(find-go-term-ctr #:report? #t)
(find-memberln-ctr #:report? #t)
(add-go-info-ctr #:report? #t)
(find-parent-ctr #:report? #t) 
```
to get usage reports. If things are still running, recall that you can use the cogserver to get addtional guile prompts:
```
(use-modules (opencog cogserver))
(start-cogserver)
```
and then
```
rlwrap telnet localhost 17001
```
BTW, @rekado if you are reading this, the reason we have a cogserver instead to using the default guile network server is twofold: (1) the cogserver is about 50x faster than the guile repl server; this makes a huge difference for moving around data, e.g. in robotics. (2) the guile network server is buggy and crashy. It will typically crash after an hour or two, which is completely unacceptable if the compute job has to stay up for months at a time. That's why the cogserver exists.  I tried to get rid of it, but no luck. (well, reason 3 is that t also provides a network shell for python, which python itself does not have).

**Comment by linas** [comment]
Some example results:
```
Time: 0.0373287 secs. calls: 1 avg:  37328.7 usec/call for smpdb
Time: 94.282941 secs. calls: 1 avg: 94282940.8 usec/call for reactome
Time: 9.7742674 secs. calls: 3 avg: 3258089.1 usec/call for find-pathway-genes
Time: 9.2660640 secs. calls: 267 avg:  34704.4 usec/call for add-pathway-genes
```
So, looks like `reactome` is eating CPU, but not clear where.

**Comment by linas** [comment]
To re-iterate the last remark ... looks like 88% of all CPU time is spent in the json library. I wouln't be surprised if that is where all the memory is leaking too, because I just don't see any memory-gobbling code anywhere in the `(annotation)` module.  It has warts and inefficiencies, but nothing quite like that.

One "obvious" solution is to proceed in a more batch-oriented fashion: first, do all the graph mining in the AtomSpace, compile the list of results, and then later hand them off to json to do whatever it is that json is doing.  You might even want to filter or cut down on the amount of data you are passing into json, as clearly, there is a CPU-explosion and likely a memory-use explosion in that component.

**Comment by linas** [comment]
FYI, I ran five more heavyweight genes: `HSP90B1 AP1G1 PPIB NDUFAF7 RBM5`, and some lightweights I didn't write down. The cumulative results are below:
```
Time: 258.70370 secs. calls: 10 avg: 25870369.8 usec/call for smpdb
Time: 561.16087 secs. calls: 10 avg: 56116087.5 usec/call for reactome
Time: 137.29761 secs. calls: 31 avg: 4428955.1 usec/call for find-pathway-genes
Time: 126.09734 secs. calls: 1668 avg:  75597.9 usec/call for add-pathway-genes
Zero calls to find-go-term
Zero calls to find-memberln
Zero calls to add-go-info
Zero calls to find-parent
Time: 0.0789199 secs. calls: 20 avg:   3946.0 usec/call for find-pathway-member
Time: 591.78595 secs. calls: 31 avg: 19089869.3 usec/call for pathway-gene-interactors
Time: 0.0199050 secs. calls: 16 avg:   1244.1 usec/call for pathway-hierarchy
Time: 2.1588711 secs. calls: 20 avg: 107943.6 usec/call for find-protein
Zero calls to find-protein-form
Time: 88.405886 secs. calls: 62 avg: 1425901.4 usec/call for find-mol
Time: 5.6221634 secs. calls: 4943 avg:   1137.4 usec/call for find-pubmed-id
```

As before, its clear that the json library is eating up almost all the CPU time. It appears that `add-pathway-genes` and `find-mol` are also eating CPU time, I believe this time its all lost in the pattern-matcher. So #88 may or may not help with that.

**Comment by linas** [comment]
Also -- please re-open and merge pull req #80 -- it was closed with no explanation. Did you click on the wrong button?

**Comment by linas** [comment]
Update: last night, I assumed that `make-parameter` was a part of json.  This morning, I searched for `make-parameter` and discovered it was part of guile.  So: new conclusion:  It's not json that is causing trouble, its the combination of the `call/cc` plus the use of `make-parameter` that is creating an explosive gobbling up of RAM and CPU.  That is, the `call/cc` is probably creating zillions of continuations, keeping them around indefinitely, eating all RAM and cycles. 

Now, the obvious thing becomes: can one redesign to not use `call/cc`? Continuations are a rather olde-fashioned way of implementing what are called "objects" in the C++ world.  It's quite easy to write objects in scheme, and you don't need goops to do that. For example:  here is a simple object with two methods:
```
(define (counter)
    (let ((cur-val 0))
        (lambda (method)
            (if  (eq? method 'incr) (set! cur-val (+ cur-val 1)))
            (if (eq? method 'decr) (set! cur-val (- cur-val 1)))
            (if (eq? method 'print) (format #t "The current value is ~A\n" cur-val))
      )))

(define my-counter  (counter))
(define another-one (counter))
(my-counter 'incr)
(my-counter 'incr)
(another-one 'decr)
(my-counter 'print)
(another-one 'print)
```

I'm proposing that the `call/cc` can be replaced by something like this,  thus explicitly controlling the state management in the system, and limiting the total RAM usage.  The point being that here, the continuation state is very simple, it's just an int called `cur-val` -- its small, its explicitly managed, and unlike call/cc, there is copy any kind of large, long, complex recursive execution state.

**Comment by rekado** [comment]
Parameters are like global variables.  They should be used sparingly.
Objects could also be implemented with Guile records, which is a little nicer than plain closures.  There are only very few situations where a full `call/cc` is the right tool.  Even when you need continuations it's better to use delimited continuations (e.g. prompts).

So yeah: what's the purpose of using `call/cc` here?

**Comment by rekado** [comment]
Generally, the code leans heavily on mutation and global state, both of which are unidiomatic in Scheme.  It seems to me that most if not all cases of mutation could be removed.  Parameters should probably be replaced with either an explicit configuration record / alist or other explicit arguments.

**Comment by linas** [comment]
After some sleep and more time to think, here's a collection of performance tuning suggestions:

* Use gcc version 7.4 or newer; this provides a 2x performance improvement over gcc-5.4 in the pattern matcher performance. The difference is just immense. In particular, Ubuntu 16.04 LTS has the old, slow version, so it's critically important to run either ubuntu-18.04 or Debian stable (or a modern version of redhat/fedora/suse, etc.)

* Start guile as `HUGETLB_MORECORE=yes LD_PRELOAD=/usr/lib/libhugetlbfs.so.0 guile` -- this can offer a 20% to 40% improvement on AtomSpace performance (in general, I have not measured the effect for this code)  The above also requires that hugepages are configured correctly.

* Get the latest atomspace code. In particular, opencog/atomspace#2464 should improve performance another 10% or 20% (based on other benchmarks; I have not measured here.)

* I kind of don't want to mention this, cause it's problematic. Try the patch below:  it improves the wall-clock time by 20% for `gene-go-annotation` (at the expense of using 2 cpu cores)
```
--- a/annotation/gene-go.scm
+++ b/annotation/gene-go.scm
@@ -28,9 +28,12 @@
     #:export (gene-go-annotation)
 )
 
+(use-modules (ice-9 threads))
+
 (define* (gene-go-annotation gene-nodes file-name #:key (namespace "biological_process molecular_function cellular_component") (parents 0) (protein "True"))
     (let (
-        [result (flatten (map (lambda (gene) 
+        [result (flatten (n-par-map 2  ; as opposed to just map.
+         (lambda (gene)
           (if (equal? protein "True")
             (ListLink
               (find-go-term (GeneNode gene) (string-split namespace #\ ) parents)
```
Why such a pitiful improvement for 2x cpu use? I'm not sure. I've fiddled with guile threading in other contexts, and its hard to get more than 2x or 3x improvement from guile threads. There's some kind of severe lock-contention/thread-thrashing when more than 3 threads are used. I have not been able to locate the root cause of this, but I strongly suspect that it's an issue deep in guile, rather than contention being in the atomspace.  

Also, (I believe)  that using `set!` is not manifestly thread-safe in guile, which is one more reason to rewrite code to be tail-recursive (or use `fold` or use `map`): those are manifestly thread-safe.

**Comment by Habush** [comment]
@linas I removed the call/cc usage completely, please check the PR

**Comment by Habush** [comment]
> Generally, the code leans heavily on mutation and global state, both of which are unidiomatic in Scheme. It seems to me that most if not all cases of mutation could be removed.

Yes, it is plagued with mutation. We wrote it like that initially because A) the code is used from python as submodule and has to maintain the state of requests B) While writing this code it was our first experience with Scheme and we had an OOP background.

Removing the mutation for the most part shouldn't be an issue ( I will send PRs). But it is difficult for the parser which has to maintain some state while parsing the scheme(Atomese?) to json.

**Comment by linas** [comment]
>  while parsing the scheme(Atomese?) to json.

Why do you need to parse anything at all? If you need to write json to a pipe or to a file, or whatever, can't you just write it directly? At any rate, none of the code that I looked at here requires json to do anything, so it's not clear why its even spec'ed in this repo.

**Comment by linas** [comment]
> call/cc

I just now tried the patch #101 and am measuring `gene-pathway-annotation` I get the following instrumentation:
```
Time: 43.445660 secs. calls: 12 avg: 3620471.7 usec/call for smpdb
Time: 2534.6847 secs. calls: 13 avg: 194975746.5 usec/call for reactome
Time: 20.328536 secs. calls: 58 avg: 350492.0 usec/call for find-pathway-genes
Time: 19.555418 secs. calls: 3771 avg:   5185.7 usec/call for add-pathway-genes
Zero calls to find-go-term
Zero calls to find-memberln
Zero calls to add-go-info
Zero calls to find-parent
Time: 0.1160833 secs. calls: 26 avg:   4464.7 usec/call for find-pathway-member
Time: 3546.3087 secs. calls: 57 avg: 62215941.9 usec/call for pathway-gene-interactors
Zero calls to generate-result
Time: 1870.1507 secs. calls: 81483 avg:  22951.4 usec/call for generate-interactors
Zero calls to build-interaction
Time: 0.3078500 secs. calls: 43 avg:   7159.3 usec/call for pathway-hierarchy
Time: 3.3938785 secs. calls: 25 avg: 135755.1 usec/call for find-protein
Zero calls to find-protein-form
Time: 35.932332 secs. calls: 116 avg: 309761.5 usec/call for find-mol
Time: 6.0779556 secs. calls: 27301 avg:    222.6 usec/call for find-name
Time: 11.885580 secs. calls: 11144 avg:   1066.5 usec/call for find-pubmed-id
```
The total CPU time, as reported by `ps aux` is 5300 seconds (about 89 minutes) of the 5300, approx 750 was spent loading the dataset, so actually, only 4550 seconds actually processing.  GC has run for 1046 seconds. Of this, there were 500 GC seconds lost in file loading, so the other 546 of GC was lost during processing. This leaves (5300 - 750 - 550) = 4000 seconds spent in actual pathway annotation.   The instrumentation found 3550 seconds in `pathway-gene-interactors` and I'm unclear as to where the remaining 400 or 500 seconds were lost.

So `pathway-gene-interactors` is actually very interesting: it is a non-trivial pattern search, exactly the kind of non-trivial search for which the pattern matcher was created for. 

Curiously, though, of that 3550 seconds, more than half was spent in `generate-interactors` and, reading through that code, it does not do anything at all fancy or complicated. So that's troubling. 

Now that I understand what `make-parameter` does, and that `biogrid-pairs-pathway` is an instance of that, I would like to suggest that there might be a better, faster substitute: use ` (make-atom-set)` from the core opencog module. I think that `(make-atom-set)` is (almost) drop-in replacement for `make-parameter` except that I'm guessing its faster, because it is fine-tuned for atoms.  (I'm not sure if its an exact drop-in replacement; I wasn't aware of `make-parameter` before. The general, overall idea seems to be the same, though. and `make-atom-set` can only ever hold atoms, and nothing else.).

**Comment by linas** [comment]
More analysis of `gene-pathway-annotation` I've now run this 4 times with parents=0 and each time, it calmly proceeds at 100% CPU for about 2 hours, when RAM usage starts to grow, slowly at first, and then ever-faster.  Examining `(gc-stats)` shows that much or most of this growth is on the guile side, not the AtomSpace side. 

To narrow this down, I've added print statements to `gene-pathway-annotation` to provide a report after it finishes each gene. Most genes take zero or one seconds; a few take 30 or 60 seconds, and maybe one out of 10 takes five minutes.  This is not surprising. I bet if I graphed this, I'd get a Zipf distribution. It would actually be an interesting graph to look at and contemplate, since it gives you a good idea of where the biological complexity lies, and where to focus software development effort. I'm not just saying this to intellecutalize: this is an actual software development technique you can apply. Nature is Zipfian. You have to be prepared for that.

Anyway, I'm monitoring the CPU times, and the length of two lists: the `result` list and the `pwlst` list. For example, processing gene `RPS20` took more than half an hour(!), and caused `(length result)` to grow to 17812 from 9882  As it did so, the guile heap size grew from 19MBytes to 26MBytes. Also, gc ran 7K times during that half-hour. (Prior to this point, gc had only run about 1K times)

Now, `RPS20` is only number 13 out of 681. So I haven't even gotten through 2% of the grand-total number of genes. .. and it has taken 60 minutes of CPU time to get this far. So estimated run-time is fifty hours.  That's a lot. If the length of `result` grows linearly like this, then it will be about 1 million long, by the end. (exept Zipfian growth isn't really linear, so I'm not sure).  Based on the gc behavior so far, I'm guessing that this will also be the cause of the guile heap explosion (which is only an hour or two away, based on prior experience -- and not fifty hours away.)

If I read the code in `gene-pathway.scm`, it seems that the only reason we need `result` is so that we can create one monster-sized atom: `(ListLink result)` https://github.com/MOZI-AI/annotation-scheme/blob/57fbdfe5d6f11af31af43489d979865ecdab8082/annotation/gene-pathway.scm#L54 which is then written to a file.  Placing such a monster-sized Atom into the AtomSpace is .. possible, certainly, but is going to be slow and wasteful, given that it is only used to write things out to a file, and then ignored and forgotten. It's pointless bloat.  If/when that file is ever read in again, the converse holds true: you will have one or two or a handful of pointlessly-huge atoms, which are unreferenced, ignored and forgotten, eating up RAM, but not being useful in any way.

Given that this also seems to be smashing the guile heap, I'm thinking that a solution here would be to write results to a pipe or file, as they are obtained, so that they don't sit in the guile heap. This alone might be enough to avoid the `Increase MAXHINCR or MAX_HEAP_SECTS` issue.

**Comment by linas** [comment]
OK, so ... 140 minutes in, the guile heap has started to grow more rapidly, we're now on gene 27 of 681, the guile heap is now 670MBytes .. but the length of `result` is only 30K so it is not that much larger: not enough to account for the enlarging heap.  Now, `pwlen` is 27 - so that is very modest, but it seems like the heap grows by 20MB or 50MB or 200MB every time that `pwlen` grows by one. So what's going on there? Another hypotheses: does this have something to do with `make-parameter`, again?

**Comment by linas** [comment]
So `biogrid-interaction-annotation` completed without any failures. It took 26.4 wall-clock hours to run, or 30.25 CPU-hours. Of this, 7.4 hours was in guile GC. At the conclusion, the guile heap was 424MB of which 294MB was free. At the conclusion, RSS=4.6GB, and Virt=9.1GB RAM.  The final atomspace contained 9M atoms, which is about double the starting size of 4.6M Atoms. The output file was 250MBytes in size (uncompressed).  

Conclusions: RAM usage seems reasonable, the GC usage is a bit outrageous, I suspect it's due to results being saved up in very long lists (as witnessed by most of the heap being free, once it completes).  Total CPU times seems outrageous; don't know where it went. Will instrument and measure.

**Comment by linas** [comment]
Summary wrap-up:  

* The issue #105 shows how to fix the RAM-usage (guile-heap) explosion bug. The annotation now uses only about 3.8GB to 4.5GB or RAM
* The issues #103 and #106 show patches that more than double the performance of `gene-pathway-annotation` and `biogrid-interaction-annotation`. Additional optimization is possible with careful code review guided by timing measurements and timing instrumentation.
* As a result of these patches, the majority of the CPU time is now spent in the pattern matcher. I've got ideas how to speed up the pattern matcher.
* Don't forget to apply the simple optimizations mentioned up above:   https://github.com/MOZI-AI/annotation-scheme/issues/98#issuecomment-570992409
* Please please please avoid creating obscenely large lists, as per comment https://github.com/MOZI-AI/annotation-scheme/issues/98#issuecomment-571434957 You don't need these lists, getting rid of them will help both the output, and the subsequent input of the data.

I think I'm more-or-less done here; I'll tweak/twerk the pattern matcher. 

One experiment not yet performed: replace the `fore-each` by `n-par-foreach 2` or `n-par-foreach 3` (or `n-par-map 2` in the following places:
https://github.com/MOZI-AI/annotation-scheme/blob/7a79385bcc59c4bae13c0843d4cb9710f2a5a3cd/annotation/gene-pathway.scm#L38
https://github.com/MOZI-AI/annotation-scheme/blob/7a79385bcc59c4bae13c0843d4cb9710f2a5a3cd/annotation/gene-go.scm#L33
https://github.com/MOZI-AI/annotation-scheme/blob/7a79385bcc59c4bae13c0843d4cb9710f2a5a3cd/annotation/biogrid.scm#L34

and see if a speedup is possible. As mentioned before, it might not be, guile parallelizes very poorly, I don't know why and it requires either Ludovic or Andy Wingo or someone of that class to figure it out.

**Comment by linas** [comment]
Closing; all suggested changes have been made.
